name: Deploy to ECS Fargate via Docker Hub

on:
  push:
    branches:
      - aula-05

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: teste-rg
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [auth-service, user-service, order-service, product-service]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug variables
        run: |
          echo "Cluster: $CLUSTER_NAME"
          echo "Service: ${{ matrix.service }}"
          echo "Image Tag: $IMAGE_TAG"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          SERVICE=${{ matrix.service }}
          echo "🚧 Building and pushing image for $SERVICE..."

          docker build -t ${{ secrets.DOCKER_USERNAME }}/$SERVICE:latest ./burguer-app/$SERVICE
          docker tag ${{ secrets.DOCKER_USERNAME }}/$SERVICE:latest \
                     ${{ secrets.DOCKER_USERNAME }}/$SERVICE:${{ github.sha }}

          docker push ${{ secrets.DOCKER_USERNAME }}/$SERVICE:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/$SERVICE:${{ github.sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Force new ECS deployment
        run: |
          SERVICE=${{ matrix.service }}
          echo "🚀 Triggering new deployment for $SERVICE on cluster $CLUSTER_NAME..."
          aws ecs update-service \
            --cluster "$CLUSTER_NAME" \
            --service "$SERVICE" \
            --region "$AWS_REGION" \
            --force-new-deployment
